package com.example.ws.services.helloworld;

import com.example.ws.types.helloworld.Greeting;
import com.example.ws.types.helloworld.Message;
import com.example.ws.types.helloworld.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-06T08:32:00.449+02:00
 * Generated source version: 3.5.2
 *
 */
@WebService(targetNamespace = "http://ws.example.com/services/helloworld", name = "HelloWorld_PortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloWorldPortType {

    @WebMethod(action = "http://ws.example.com/services/helloworld/greeting")
    @WebResult(name = "greeting", targetNamespace = "http://ws.example.com/types/helloworld", partName = "greeting")
    public Greeting greeting(

        @WebParam(partName = "message", name = "message", targetNamespace = "http://ws.example.com/types/helloworld")
                Message message
    );
}
